services:
  postgres:
    container_name: postgres
    image: 'postgres:16.3-alpine'
    environment:
      - 'POSTGRES_DB=spring-boot-testcontainers'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - spring-boot-testcontainers
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:3.13.6-management-alpine'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - spring-boot-testcontainers

networks:
  spring-boot-testcontainers:
    driver: bridge
