spring:
  application:
    name: spring-boot-template
    jackson:
      property-naming-strategy: SNAKE_CASE
    flyway:
      locations: classpath:/db/migration
      schemas: employee
      baselineOnMigrate: true
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#RabbitMQ
rabbitmq:
  queue:
    name: sbtc-employees-queue
    exchange: sbtc-employees-exchange
    routing-key: sbtc-employees-routing-key
