spring:
  application:
    name: spring-boot-testcontainers
    jackson:
      property-naming-strategy: SNAKE_CASE
    flyway:
      locations: classpath:/db/migration
      schemas: employee
      baselineOnMigrate: true
      enabled: true

rabbitmq:
  employees:
    exchange: sbtc-employees-exchange
    create:
      queue: sbtc-create-employees-queue
      routing-key: sbtc-create-employees-routing-key
    update:
      queue: sbtc-update-employees-queue
      routing-key: sbtc-update-employees-routing-key
